### PR TITLE
Add Equiv and fix references from other projects

### PR DESCRIPTION
**Pull request by SReichelt**
This PR adds those parts of `Equiv` that I need in my own project (https://github.com/SReichelt/lean4-experiments).

To be able to reference `mathlib4_experiments`, I needed to rename the `src` directory. It seems that the name needs to match the top-level `.lean` file. Other than that I think it can be chosen freely, but `src` is problematic if it is referenced externally.

### CODE REVIEW

**Comment by kbuzzard** [comment]
Oh sorry -- I only just saw this! I'm not very good at github and assumed nobody was looking at this repo. I'll try and merge this!

**Comment by kbuzzard** [comment]
OK I think I've got it merged. I had independently run into the `src` problem.

**Comment by SReichelt** [comment]
Thanks. :-) Looks like everything worked; I was able to simply update the mathlib4_experiments reference.
(I'm aware that isn't really the purpose of this repo, but it's still nice to have a separation between "something mathlib-like" and my own repo.)

**Comment by kbuzzard** [comment]
The purpose of this repo is simply to teach myself some Lean 4 by formalising material I'm familiar with from Lean 3. I'm completely happy for you to use it the way you're using it.

**Pull request merged**
